//
// Created by david on 1/22/2023.
//

#ifndef SORTINGALGORITHMSVISUALIZATION_CONSTANTS_H
#define SORTINGALGORITHMSVISUALIZATION_CONSTANTS_H

typedef unsigned char byte;

#define BARS 40
#define BAR_WIDTH 10
#define BAR_HEIGHT 6
#define PIXEL_WIDTH 2
#define PIXEL_HEIGHT 2

#endif //SORTINGALGORITHMSVISUALIZATION_CONSTANTS_H
