//
// Created by david on 1/22/2023.
//

#ifndef SORTINGALGORITHMSVISUALIZATION_CONSTANTS_H
#define SORTINGALGORITHMSVISUALIZATION_CONSTANTS_H

#define COLUMNS 50
#define COLUMN_WIDTH 10
#define COLUMN_HEIGHT 5
#define PIXEL_WIDTH 2
#define PIXEL_HEIGHT 2

#endif //SORTINGALGORITHMSVISUALIZATION_CONSTANTS_H
